// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAQYgK0h9qge9zvLhQ5JSEHXcxtobztTw',
    appId: '1:835854512718:web:0ab503712851ce9d64091f',
    messagingSenderId: '835854512718',
    projectId: 'smart-socks-2d556',
    authDomain: 'smart-socks-2d556.firebaseapp.com',
    storageBucket: 'smart-socks-2d556.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVbeMq6Tp-Z-T0ugPDGCvPt1o9EDb6Ew',
    appId: '1:835854512718:android:71f192aa54644f7064091f',
    messagingSenderId: '835854512718',
    projectId: 'smart-socks-2d556',
    storageBucket: 'smart-socks-2d556.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB74fMjfhdnSC3W_f6AvPcMyZ_L9JD4J8',
    appId: '1:835854512718:ios:f13e96cf95f1026064091f',
    messagingSenderId: '835854512718',
    projectId: 'smart-socks-2d556',
    storageBucket: 'smart-socks-2d556.firebasestorage.app',
    iosBundleId: 'com.example.smartSocks',
  );
}
