import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';
import '../../core/constants/app_colors.dart';

/// Represents an alert or warning generated by the system
class Alert extends Equatable {
  /// Unique identifier for the alert
  final String id;

  /// Type of alert (temperature, pressure, circulation, gait)
  final AlertType type;

  /// Severity level (info, warning, critical)
  final AlertSeverity severity;

  /// Alert title (short description)
  final String title;

  /// Detailed alert message
  final String message;

  /// Affected foot zone (if applicable)
  final String? affectedZone;

  /// The actual sensor value that triggered the alert
  final double? actualValue;

  /// The threshold that was exceeded
  final double? threshold;

  /// When the alert was generated
  final DateTime timestamp;

  /// Whether the user has seen/acknowledged this alert
  final bool isRead;

  /// Recommended action (if any)
  final String? action;

  /// Additional metadata
  final Map<String, dynamic>? metadata;

  const Alert({
    required this.id,
    required this.type,
    required this.severity,
    required this.title,
    required this.message,
    this.affectedZone,
    this.actualValue,
    this.threshold,
    required this.timestamp,
    this.isRead = false,
    this.action,
    this.metadata,
  });

  /// Create a new alert with auto-generated ID
  factory Alert.create({
    required AlertType type,
    required AlertSeverity severity,
    required String title,
    required String message,
    String? affectedZone,
    double? actualValue,
    double? threshold,
    DateTime? timestamp,
    String? action,
    Map<String, dynamic>? metadata,
  }) {
    return Alert(
      id: const Uuid().v4(),
      type: type,
      severity: severity,
      title: title,
      message: message,
      affectedZone: affectedZone,
      actualValue: actualValue,
      threshold: threshold,
      timestamp: timestamp ?? DateTime.now(),
      isRead: false,
      action: action,
      metadata: metadata,
    );
  }

  // ============== Factory Methods for Common Alerts ==============

  /// Create a high temperature alert
  factory Alert.highTemperature({
    required String zone,
    required double temperature,
    required double threshold,
  }) {
    final severity = temperature > threshold + 2 
        ? AlertSeverity.critical 
        : AlertSeverity.warning;
    
    return Alert.create(
      type: AlertType.temperature,
      severity: severity,
      title: 'High Temperature',
      message: '$zone area showing elevated temperature '
          '(${temperature.toStringAsFixed(1)}°C). '
          'This may indicate inflammation or infection risk.',
      affectedZone: zone,
      actualValue: temperature,
      threshold: threshold,
      action: 'Apply cool compress and monitor for changes',
    );
  }

  /// Create a high pressure alert
  factory Alert.highPressure({
    required String zone,
    required double pressure,
    required double threshold,
  }) {
    final severity = pressure > threshold * 1.2 
        ? AlertSeverity.critical 
        : AlertSeverity.warning;
    
    return Alert.create(
      type: AlertType.pressure,
      severity: severity,
      title: 'High Pressure',
      message: '$zone area experiencing high pressure '
          '(${pressure.toStringAsFixed(1)} kPa). '
          'Prolonged pressure may cause tissue damage.',
      affectedZone: zone,
      actualValue: pressure,
      threshold: threshold,
      action: 'Redistribute weight or change position',
    );
  }

  /// Create a low SpO2 alert
  factory Alert.lowSpO2({
    required double spO2,
    required double threshold,
  }) {
    final severity = spO2 < threshold - 5 
        ? AlertSeverity.critical 
        : AlertSeverity.warning;
    
    return Alert.create(
      type: AlertType.circulation,
      severity: severity,
      title: 'Low Blood Oxygen',
      message: 'Blood oxygen level is low (${spO2.toStringAsFixed(1)}%). '
          'This may indicate poor circulation.',
      actualValue: spO2,
      threshold: threshold,
      action: 'Move around to improve circulation',
    );
  }

  /// Create a temperature asymmetry alert
  factory Alert.temperatureAsymmetry({
    required double difference,
    required double threshold,
    required String hotterZone,
  }) {
    return Alert.create(
      type: AlertType.temperature,
      severity: AlertSeverity.warning,
      title: 'Temperature Asymmetry',
      message: 'Temperature difference of ${difference.toStringAsFixed(1)}°C '
          'detected. $hotterZone is warmer than other areas.',
      affectedZone: hotterZone,
      actualValue: difference,
      threshold: threshold,
      action: 'Monitor the warmer area for changes',
    );
  }

  /// Create a gait abnormality alert
  factory Alert.gaitAbnormality({
    required String description,
    double? stabilityScore,
  }) {
    return Alert.create(
      type: AlertType.gait,
      severity: AlertSeverity.info,
      title: 'Gait Pattern Change',
      message: description,
      actualValue: stabilityScore,
      action: 'Walk carefully and use support if needed',
    );
  }

  /// Create a battery low alert
  factory Alert.batteryLow({
    required int level,
  }) {
    final severity = level < 10 
        ? AlertSeverity.critical 
        : AlertSeverity.warning;
    
    return Alert.create(
      type: AlertType.system,
      severity: severity,
      title: 'Battery Low',
      message: 'Device battery is at $level%. '
          'Please charge soon to continue monitoring.',
      actualValue: level.toDouble(),
      action: 'Charge your smart sock device',
    );
  }

  /// Create a connection lost alert
  factory Alert.connectionLost() {
    return Alert.create(
      type: AlertType.system,
      severity: AlertSeverity.warning,
      title: 'Connection Lost',
      message: 'Lost connection to smart sock device. '
          'Monitoring has been paused.',
      action: 'Check device and reconnect',
    );
  }

  // ============== Getters ==============

  /// Get the color for this alert
  Color get color => severity.color;

  /// Get the background color for this alert
  Color get backgroundColor => severity.backgroundColor;

  /// Get the icon for this alert
  IconData get icon => type.icon;

  /// Get severity icon
  IconData get severityIcon => severity.icon;

  /// Check if this is a critical alert
  bool get isCritical => severity == AlertSeverity.critical;

  /// Check if this alert requires immediate attention
  bool get requiresAttention => 
      severity == AlertSeverity.critical || 
      severity == AlertSeverity.warning;

  /// Get formatted timestamp
  String get formattedTime {
    final now = DateTime.now();
    final diff = now.difference(timestamp);

    if (diff.inMinutes < 1) {
      return 'Just now';
    } else if (diff.inMinutes < 60) {
      return '${diff.inMinutes}m ago';
    } else if (diff.inHours < 24) {
      return '${diff.inHours}h ago';
    } else if (diff.inDays < 7) {
      return '${diff.inDays}d ago';
    } else {
      return '${timestamp.day}/${timestamp.month}/${timestamp.year}';
    }
  }

  /// Get value comparison string (e.g., "35.5°C > 35.0°C threshold")
  String? get valueComparison {
    if (actualValue == null || threshold == null) return null;
    
    final unit = type == AlertType.temperature 
        ? '°C' 
        : type == AlertType.pressure 
            ? 'kPa' 
            : '%';
    
    return '${actualValue!.toStringAsFixed(1)}$unit > '
           '${threshold!.toStringAsFixed(1)}$unit threshold';
  }

  // ============== Serialization ==============

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'type': type.name,
      'severity': severity.name,
      'title': title,
      'message': message,
      'affectedZone': affectedZone,
      'actualValue': actualValue,
      'threshold': threshold,
      'timestamp': timestamp.millisecondsSinceEpoch,
      'isRead': isRead,
      'action': action,
      'metadata': metadata,
    };
  }

  factory Alert.fromJson(Map<String, dynamic> json) {
    return Alert(
      id: json['id'] ?? const Uuid().v4(),
      type: AlertType.fromString(json['type']),
      severity: AlertSeverity.fromString(json['severity']),
      title: json['title'] ?? 'Alert',
      message: json['message'] ?? '',
      affectedZone: json['affectedZone'],
      actualValue: json['actualValue']?.toDouble(),
      threshold: json['threshold']?.toDouble(),
      timestamp: DateTime.fromMillisecondsSinceEpoch(
        json['timestamp'] ?? DateTime.now().millisecondsSinceEpoch,
      ),
      isRead: json['isRead'] ?? false,
      action: json['action'],
      metadata: json['metadata'],
    );
  }

  /// Create a copy with modified fields
  Alert copyWith({
    String? id,
    AlertType? type,
    AlertSeverity? severity,
    String? title,
    String? message,
    String? affectedZone,
    double? actualValue,
    double? threshold,
    DateTime? timestamp,
    bool? isRead,
    String? action,
    Map<String, dynamic>? metadata,
  }) {
    return Alert(
      id: id ?? this.id,
      type: type ?? this.type,
      severity: severity ?? this.severity,
      title: title ?? this.title,
      message: message ?? this.message,
      affectedZone: affectedZone ?? this.affectedZone,
      actualValue: actualValue ?? this.actualValue,
      threshold: threshold ?? this.threshold,
      timestamp: timestamp ?? this.timestamp,
      isRead: isRead ?? this.isRead,
      action: action ?? this.action,
      metadata: metadata ?? this.metadata,
    );
  }

  /// Mark this alert as read
  Alert markAsRead() => copyWith(isRead: true);

  @override
  List<Object?> get props => [
        id,
        type,
        severity,
        title,
        message,
        affectedZone,
        actualValue,
        threshold,
        timestamp,
        isRead,
        action,
        metadata,
      ];

  @override
  String toString() => 
      'Alert(${severity.name}: $title - $message)';
}

/// Types of alerts
enum AlertType {
  temperature,
  pressure,
  circulation,
  gait,
  system;

  static AlertType fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'temperature':
        return AlertType.temperature;
      case 'pressure':
        return AlertType.pressure;
      case 'circulation':
        return AlertType.circulation;
      case 'gait':
        return AlertType.gait;
      case 'system':
        return AlertType.system;
      default:
        return AlertType.system;
    }
  }

  /// Display name for UI
  String get displayName {
    switch (this) {
      case AlertType.temperature:
        return 'Temperature';
      case AlertType.pressure:
        return 'Pressure';
      case AlertType.circulation:
        return 'Circulation';
      case AlertType.gait:
        return 'Gait';
      case AlertType.system:
        return 'System';
    }
  }

  /// Icon for this alert type
  IconData get icon {
    switch (this) {
      case AlertType.temperature:
        return Icons.thermostat;
      case AlertType.pressure:
        return Icons.compress;
      case AlertType.circulation:
        return Icons.favorite;
      case AlertType.gait:
        return Icons.directions_walk;
      case AlertType.system:
        return Icons.settings;
    }
  }

  /// Color for this alert type
  Color get color {
    switch (this) {
      case AlertType.temperature:
        return AppColors.temperature;
      case AlertType.pressure:
        return AppColors.pressure;
      case AlertType.circulation:
        return AppColors.oxygen;
      case AlertType.gait:
        return AppColors.gait;
      case AlertType.system:
        return AppColors.primary;
    }
  }
}

/// Severity levels for alerts
enum AlertSeverity {
  info,
  warning,
  critical;

  static AlertSeverity fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'info':
        return AlertSeverity.info;
      case 'warning':
        return AlertSeverity.warning;
      case 'critical':
        return AlertSeverity.critical;
      default:
        return AlertSeverity.info;
    }
  }

  /// Display name for UI
  String get displayName {
    switch (this) {
      case AlertSeverity.info:
        return 'Info';
      case AlertSeverity.warning:
        return 'Warning';
      case AlertSeverity.critical:
        return 'Critical';
    }
  }

  /// Color for this severity
  Color get color {
    switch (this) {
      case AlertSeverity.info:
        return AppColors.info;
      case AlertSeverity.warning:
        return AppColors.warning;
      case AlertSeverity.critical:
        return AppColors.error;
    }
  }

  /// Background color for this severity
  Color get backgroundColor {
    switch (this) {
      case AlertSeverity.info:
        return AppColors.infoLight;
      case AlertSeverity.warning:
        return AppColors.warningLight;
      case AlertSeverity.critical:
        return AppColors.errorLight;
    }
  }

  /// Icon for this severity
  IconData get icon {
    switch (this) {
      case AlertSeverity.info:
        return Icons.info_outline;
      case AlertSeverity.warning:
        return Icons.warning_amber;
      case AlertSeverity.critical:
        return Icons.error;
    }
  }

  /// Priority value (higher = more urgent)
  int get priority {
    switch (this) {
      case AlertSeverity.info:
        return 1;
      case AlertSeverity.warning:
        return 2;
      case AlertSeverity.critical:
        return 3;
    }
  }
}
